- name: "Ianseo Provisioning"
  hosts: all
  remote_user: root

  tasks:
  - name: "Upgrade distribution"
    ansible.builtin.apt:
        update_cache: yes
        upgrade: full

  - name: "Install utilities"
    ansible.builtin.apt:
      pkg:
        - zabbix-agent
        - unzip

  - name: "Install Apache2"
    ansible.builtin.apt:
      name: apache2

  - name: "Install MariaDB"
    ansible.builtin.apt:
      pkg:
        - mariadb-server
        - python3-mysqldb

  - name: "Install PHP8.2 and modules"
    ansible.builtin.apt:
      pkg:
        - php8.2
        - php8.2-curl
        - php8.2-mysql
        - php8.2-gd
        - php8.2-mbstring
        - php8.2-mcrypt
        - php8.2-xml
        - php8.2-zip
        - php8.2-imagick
        - imagemagick
        - libapache2-mod-php8.2

  - name: "Create Ianseo Directory"
    ansible.builtin.file:
      path: /var/www/html/
      state: directory
      mode: a+wX

  - name: "Download and extract last version of Ianseo"
    ansible.builtin.unarchive:
      src: https://www.ianseo.net/Release/Ianseo_20230401.zip
      dest: /var/www/html/
      remote_src: yes

  - name: "Erase Ianseo config.inc.php file"
    ansible.builtin.file:
      path: /var/www/html/Common/config.inc.php
      state: absent

  - name: "Empty www folder"
    ansible.builtin.file:
      path: /var/www/html/indx.html
      state: absent

  - name: "Change permissions on Ianseo Directory"
    ansible.builtin.file:
      path: /var/www/html/
      state: directory
      mode: a+wX
      recurse: yes
      owner: www-data
      group: www-data

  - name: "Tuning PHP8 configuration"
    ansible.builtin.copy:
      src: ianseo.ini
      dest: /etc/php/8.2/apache2/conf.d/ianseo.ini

  - name: "Tuning MariaDB configuration"
    ansible.builtin.copy:
      src: ianseo.cnf
      dest: /etc/mysql/mariadb.conf.d/ianseo.cnf

  - name: "Copy Ianseo configuration for Apache2"
    ansible.builtin.copy:
      src: ianseo.conf
      dest: /etc/apache2/conf-available/ianseo.conf

  - name: "Enable Ianseo configuration for Apache2"
    ansible.builtin.command:
      cmd: a2enconf ianseo

  - name: "Restart Apache2"
    ansible.builtin.command:
      cmd: service apache2 restart

  - name: "Restart MariaDB"
    ansible.builtin.command:
      cmd: service mariadb restart

  - name: "Create Ianseo database"
    community.mysql.mysql_db:
      name: ianseo
      state: present

  - name: "Import Ianseo database"
    community.mysql.mysql_db:
      name: ianseo
      state: import
      target: /var/www/html/Install/install.sql
      login_user: ianseo
      login_password: "ianseo"

  - name: "Create Ianseo MySQL User"
    community.mysql.mysql_user:
      name: ianseo
      password: ianseo
      host: localhost
      priv:
        'ianseo.*': 'ALL,GRANT'
